version: '3.8'

services:
  # Next.js Application (Development Mode)
  nextjs-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-dev-secret-key}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - ENABLE_ANALYTICS=${ENABLE_ANALYTICS:-false}
      - ENABLE_DEBUG_MODE=${ENABLE_DEBUG_MODE:-true}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env
      - .env.development
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - nextjs-network

  # Redis (for caching and sessions)
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - nextjs-network

  # Redis Commander (Redis management UI)
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin123
    depends_on:
      - redis
    networks:
      - nextjs-network

volumes:
  redis_data:

networks:
  nextjs-network:
    driver: bridge
