version: '3.8'

services:
  nextjs-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
      # Add other environment variables you need
    restart: unless-stopped